name: Glass Images
favicon: null
layout_spectrum: 0.25933
typography_spectrum: 0.24729
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#808588'
    - '#b9c5d1'
    - '#a0a2ae'
    - '#46474b'
  brandStrength: 0.477708728518337
  lightness: 0.3278651579748839
  saturation: 0.9425004427321255
  rhythmicContrast: 0.25
purpose: []
