name: Glass Images
favicon: null
layout_spectrum: 0.37899904139339924
typography_spectrum: 0.6796590548474342
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010100'
    - '#4d1000'
    - '#f5f2e3'
    - '#dfb680'
    - '#7c5b2e'
  brandStrength: 0.477708728518337
  lightness: 0.3278651579748839
  saturation: 0.9425004427321255
  rhythmicContrast: 0.25
purpose: []
