typography_spectrum: 0.76233
color:
  brandColors:
    - '#ffffff'
    - '#808588'
    - '#b9c5d1'
    - '#a0a2ae'
    - '#46474b'
  brandStrength: 1
  lightness: 0.1875
  saturation: 0.0625
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.74789
analytics:
  google: null
  facebook: null
  twitter: null
name: Glass Images
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Glass Images & Creations inc.
description: architectural statements in glass
purpose: []
