name: Glass Images
favicon: null
layout_spectrum: 0.23646
typography_spectrum: 0.75632
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#808588'
    - '#b9c5d1'
    - '#a0a2ae'
    - '#46474b'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.8125
  rhythmicContrast: 0.5
purpose: []
